"""Added auto increment fields in user and category

Revision ID: 9c8e28ccc9d7
Revises: 310b1e9297e9
Create Date: 2025-09-09 11:11:40.482146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8e28ccc9d7'
down_revision: Union[str, Sequence[str], None] = '310b1e9297e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
